apiVersion: v2
name: fastetcd
description: A Rust implementation of the etcd v3 wire protocol
type: application
version: 0.2.0
appVersion: "1.20.1"
home: https://github.com/glennswest/fastetcd
sources:
  - https://github.com/glennswest/fastetcd
maintainers:
  - name: fastetcd contributors
