#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
  if [ -d /run/systemd/system ]; then
    systemctl disable fastetcd.service >/dev/null 2>&1 || true
    systemctl daemon-reload >/dev/null 2>&1 || true
  fi
fi

if [ "$1" = "purge" ]; then
  rm -rf /etc/fastetcd
  if getent passwd fastetcd >/dev/null; then
    deluser --system fastetcd >/dev/null 2>&1 || true
  fi
  if getent group fastetcd >/dev/null; then
    delgroup --system fastetcd >/dev/null 2>&1 || true
  fi
fi

exit 0
