//! etcd's v3 JSON gateway (fastetcd#28): `POST /v3/...` on the client
//! port, beside `/health`, so HTTP tools (a console, `curl`) can use the
//! etcd API without a gRPC client.
//!
//! It is etcd's own surface, as etcd v3.6 serves it (grpc-gateway v2,
//! `server/embed/serve.go`), so recipes and tools written against etcd
//! work unchanged:
//!
//! - Routes are the `google.api.http` annotations of etcd's `rpc.proto`
//!   (see [`router`]). Every call is a `POST` whose body is the request
//!   message as JSON; an empty body is the default request.
//! - JSON is protojson with `UseProtoNames` and no default fields: proto
//!   field names (`raft_term`, `dbSize`, `ID`), 64-bit integers as
//!   strings, bytes (keys and values) base64, enums by name. Input takes
//!   either field spelling, and unknown fields are ignored. The serde
//!   impls are generated by pbjson (`fastetcd-proto`).
//! - An error is the HTTP status grpc-gateway maps its gRPC code to,
//!   with body `{"code":N,"message":"…"}`.
//! - A streamed response (`/v3/maintenance/snapshot`) is one JSON object
//!   per line: `{"result":{…}}`, or `{"error":{"code":N,"message":"…"}}`.
//!
//! Nothing here is new behaviour: each call is decoded, passed through
//! the same [`AuthInterceptor`] as gRPC (the token comes from the
//! `Authorization` header, as etcd's gateway forwards it; a TLS client
//! certificate's CN identifies the caller exactly as over gRPC), and
//! handed to the same service implementation, whose own permission
//! checks then apply. Calls are counted in `grpc_server_*_total` under
//! the method they call, as etcd's are (its gateway dials the gRPC
//! server).

use std::future::Future;
use std::sync::Arc;

use axum::body::{Body, Bytes};
use axum::extract::{Request, State};
use axum::http::{header, HeaderValue, StatusCode};
use axum::response::Response;
use axum::routing::post;
use axum::Router;
use fastetcd_proto::etcdserverpb as pb;
use fastetcd_proto::etcdserverpb::auth_server::Auth;
use fastetcd_proto::etcdserverpb::cluster_server::Cluster;
use fastetcd_proto::etcdserverpb::kv_server::Kv;
use fastetcd_proto::etcdserverpb::lease_server::Lease;
use fastetcd_proto::etcdserverpb::maintenance_server::Maintenance;
use futures::StreamExt;
use serde::de::DeserializeOwned;
use serde::Serialize;
use tonic::service::Interceptor;
use tonic::{Code, Status};

use crate::auth::{AuthInterceptor, AuthService};
use crate::cluster::ClusterService;
use crate::kv::KvService;
use crate::lease::LeaseService;
use crate::maintenance::MaintenanceService;
use crate::traffic::{code_label, GrpcHandledLabels, GrpcLabels, Traffic};

/// Largest request body accepted (etcd's default max request is 1.5 MiB
/// plus gRPC overhead; JSON and base64 make that roughly 2 MiB more).
const MAX_BODY: usize = 4 * 1024 * 1024;

/// The services the gateway calls, the interceptor in front of them,
/// and the traffic counters.
#[derive(Clone)]
pub struct Gateway {
    pub kv: KvService,
    pub lease: LeaseService,
    pub cluster: ClusterService,
    pub maintenance: MaintenanceService,
    pub auth: AuthService,
    pub interceptor: AuthInterceptor,
    pub traffic: Arc<Traffic>,
}

/// The gateway's routes, to merge into the client port's router.
pub fn router(gw: Gateway) -> Router {
    // One route per etcd method. `$intercept` is false only for Auth,
    // which is not behind the interceptor over gRPC either (it resolves
    // its caller itself, so `Authenticate` works without a token).
    macro_rules! unary {
        ($r:expr, $path:literal, $svc:literal, $method:literal,
         $field:ident, $tr:ident :: $f:ident, $req:ident, $intercept:expr) => {
            $r.route(
                $path,
                post(|State(gw): State<Arc<Gateway>>, req: Request| async move {
                    unary(gw, req, $svc, $method, $intercept, |gw, r: tonic::Request<pb::$req>| async move {
                        $tr::$f(&gw.$field, r).await
                    })
                    .await
                }),
            )
        };
    }
    let r = Router::new();
    // KV
    let r = unary!(r, "/v3/kv/range", "KV", "Range", kv, Kv::range, RangeRequest, true);
    let r = unary!(r, "/v3/kv/put", "KV", "Put", kv, Kv::put, PutRequest, true);
    let r = unary!(r, "/v3/kv/deleterange", "KV", "DeleteRange", kv, Kv::delete_range, DeleteRangeRequest, true);
    let r = unary!(r, "/v3/kv/txn", "KV", "Txn", kv, Kv::txn, TxnRequest, true);
    let r = unary!(r, "/v3/kv/compaction", "KV", "Compact", kv, Kv::compact, CompactionRequest, true);
    // Lease (the `/v3/kv/lease/*` paths are etcd's additional bindings)
    let r = unary!(r, "/v3/lease/grant", "Lease", "LeaseGrant", lease, Lease::lease_grant, LeaseGrantRequest, true);
    let r = unary!(r, "/v3/lease/revoke", "Lease", "LeaseRevoke", lease, Lease::lease_revoke, LeaseRevokeRequest, true);
    let r = unary!(r, "/v3/kv/lease/revoke", "Lease", "LeaseRevoke", lease, Lease::lease_revoke, LeaseRevokeRequest, true);
    let r = unary!(r, "/v3/lease/timetolive", "Lease", "LeaseTimeToLive", lease, Lease::lease_time_to_live, LeaseTimeToLiveRequest, true);
    let r = unary!(r, "/v3/kv/lease/timetolive", "Lease", "LeaseTimeToLive", lease, Lease::lease_time_to_live, LeaseTimeToLiveRequest, true);
    let r = unary!(r, "/v3/lease/leases", "Lease", "LeaseLeases", lease, Lease::lease_leases, LeaseLeasesRequest, true);
    let r = unary!(r, "/v3/kv/lease/leases", "Lease", "LeaseLeases", lease, Lease::lease_leases, LeaseLeasesRequest, true);
    // Cluster
    let r = unary!(r, "/v3/cluster/member/add", "Cluster", "MemberAdd", cluster, Cluster::member_add, MemberAddRequest, true);
    let r = unary!(r, "/v3/cluster/member/remove", "Cluster", "MemberRemove", cluster, Cluster::member_remove, MemberRemoveRequest, true);
    let r = unary!(r, "/v3/cluster/member/update", "Cluster", "MemberUpdate", cluster, Cluster::member_update, MemberUpdateRequest, true);
    let r = unary!(r, "/v3/cluster/member/list", "Cluster", "MemberList", cluster, Cluster::member_list, MemberListRequest, true);
    let r = unary!(r, "/v3/cluster/member/promote", "Cluster", "MemberPromote", cluster, Cluster::member_promote, MemberPromoteRequest, true);
    // Maintenance
    let r = unary!(r, "/v3/maintenance/alarm", "Maintenance", "Alarm", maintenance, Maintenance::alarm, AlarmRequest, true);
    let r = unary!(r, "/v3/maintenance/status", "Maintenance", "Status", maintenance, Maintenance::status, StatusRequest, true);
    let r = unary!(r, "/v3/maintenance/defragment", "Maintenance", "Defragment", maintenance, Maintenance::defragment, DefragmentRequest, true);
    let r = unary!(r, "/v3/maintenance/hash", "Maintenance", "Hash", maintenance, Maintenance::hash, HashRequest, true);
    let r = unary!(r, "/v3/maintenance/hashkv", "Maintenance", "HashKV", maintenance, Maintenance::hash_kv, HashKvRequest, true);
    let r = unary!(r, "/v3/maintenance/transfer-leadership", "Maintenance", "MoveLeader", maintenance, Maintenance::move_leader, MoveLeaderRequest, true);
    let r = unary!(r, "/v3/maintenance/downgrade", "Maintenance", "Downgrade", maintenance, Maintenance::downgrade, DowngradeRequest, true);
    let r = r.route("/v3/maintenance/snapshot", post(snapshot));
    // Auth
    let r = unary!(r, "/v3/auth/enable", "Auth", "AuthEnable", auth, Auth::auth_enable, AuthEnableRequest, false);
    let r = unary!(r, "/v3/auth/disable", "Auth", "AuthDisable", auth, Auth::auth_disable, AuthDisableRequest, false);
    let r = unary!(r, "/v3/auth/status", "Auth", "AuthStatus", auth, Auth::auth_status, AuthStatusRequest, false);
    let r = unary!(r, "/v3/auth/authenticate", "Auth", "Authenticate", auth, Auth::authenticate, AuthenticateRequest, false);
    let r = unary!(r, "/v3/auth/user/add", "Auth", "UserAdd", auth, Auth::user_add, AuthUserAddRequest, false);
    let r = unary!(r, "/v3/auth/user/get", "Auth", "UserGet", auth, Auth::user_get, AuthUserGetRequest, false);
    let r = unary!(r, "/v3/auth/user/list", "Auth", "UserList", auth, Auth::user_list, AuthUserListRequest, false);
    let r = unary!(r, "/v3/auth/user/delete", "Auth", "UserDelete", auth, Auth::user_delete, AuthUserDeleteRequest, false);
    let r = unary!(r, "/v3/auth/user/changepw", "Auth", "UserChangePassword", auth, Auth::user_change_password, AuthUserChangePasswordRequest, false);
    let r = unary!(r, "/v3/auth/user/grant", "Auth", "UserGrantRole", auth, Auth::user_grant_role, AuthUserGrantRoleRequest, false);
    let r = unary!(r, "/v3/auth/user/revoke", "Auth", "UserRevokeRole", auth, Auth::user_revoke_role, AuthUserRevokeRoleRequest, false);
    let r = unary!(r, "/v3/auth/role/add", "Auth", "RoleAdd", auth, Auth::role_add, AuthRoleAddRequest, false);
    let r = unary!(r, "/v3/auth/role/get", "Auth", "RoleGet", auth, Auth::role_get, AuthRoleGetRequest, false);
    let r = unary!(r, "/v3/auth/role/list", "Auth", "RoleList", auth, Auth::role_list, AuthRoleListRequest, false);
    let r = unary!(r, "/v3/auth/role/delete", "Auth", "RoleDelete", auth, Auth::role_delete, AuthRoleDeleteRequest, false);
    let r = unary!(r, "/v3/auth/role/grant", "Auth", "RoleGrantPermission", auth, Auth::role_grant_permission, AuthRoleGrantPermissionRequest, false);
    let r = unary!(r, "/v3/auth/role/revoke", "Auth", "RoleRevokePermission", auth, Auth::role_revoke_permission, AuthRoleRevokePermissionRequest, false);
    // Anything else under /v3/ is grpc-gateway's JSON 404, not the gRPC
    // router's `Unimplemented`.
    let r = r.route("/v3/*rest", axum::routing::any(not_found));
    r.with_state(Arc::new(gw))
}

async fn not_found() -> Response {
    error(&Status::not_found("Not Found"))
}

/// One unary call: decode, authenticate, call, encode.
async fn unary<Req, Resp, F, Fut>(
    gw: Arc<Gateway>,
    req: Request,
    service: &'static str,
    method: &'static str,
    intercept: bool,
    call: F,
) -> Response
where
    Req: DeserializeOwned + Default,
    Resp: Serialize,
    F: FnOnce(Arc<Gateway>, tonic::Request<Req>) -> Fut,
    Fut: Future<Output = Result<tonic::Response<Resp>, Status>>,
{
    let mut counted = Counted::start(&gw.traffic, service, method, "unary");
    let result = match decode::<Req>(&gw, req, intercept).await {
        Ok(request) => call(gw.clone(), request).await,
        Err(status) => Err(status),
    };
    match result {
        Ok(resp) => {
            counted.finish(Code::Ok);
            match serde_json::to_vec(resp.get_ref()) {
                Ok(body) => json(StatusCode::OK, body),
                Err(e) => error(&Status::internal(format!("encode response: {e}"))),
            }
        }
        Err(status) => {
            counted.finish(status.code());
            error(&status)
        }
    }
}

/// `POST /v3/maintenance/snapshot`: the snapshot stream, one
/// `{"result":{"remaining_bytes":…,"blob":"<base64>"}}` per line.
async fn snapshot(State(gw): State<Arc<Gateway>>, req: Request) -> Response {
    let mut counted = Counted::start(&gw.traffic, "Maintenance", "Snapshot", "server_stream");
    let request = match decode::<pb::SnapshotRequest>(&gw, req, true).await {
        Ok(r) => r,
        Err(status) => {
            counted.finish(status.code());
            return error(&status);
        }
    };
    let stream = match Maintenance::snapshot(&gw.maintenance, request).await {
        Ok(resp) => resp.into_inner(),
        Err(status) => {
            counted.finish(status.code());
            return error(&status);
        }
    };
    let lines = futures::stream::unfold((stream, counted, false), |(mut s, mut counted, done)| async move {
        if done {
            return None;
        }
        match s.next().await {
            Some(Ok(msg)) => Some((result_line(&msg), (s, counted, false))),
            // grpc-gateway ends the stream after an error.
            Some(Err(status)) => {
                counted.finish(status.code());
                Some((error_line(&status), (s, counted, true)))
            }
            None => {
                counted.finish(Code::Ok);
                None
            }
        }
    });
    let mut resp = Response::new(Body::from_stream(
        lines.map(Ok::<_, std::convert::Infallible>),
    ));
    resp.headers_mut()
        .insert(header::CONTENT_TYPE, HeaderValue::from_static("application/json"));
    resp
}

/// The request as the service expects it: the JSON body as the message,
/// the `Authorization` header as `authorization` metadata (as etcd's
/// gateway forwards it), the connection's extensions (TLS peer
/// certificates) carried over, and, unless `intercept` is false, passed
/// through the auth interceptor exactly as a gRPC call is.
async fn decode<Req: DeserializeOwned + Default>(
    gw: &Gateway,
    req: Request,
    intercept: bool,
) -> Result<tonic::Request<Req>, Status> {
    let (parts, body) = req.into_parts();
    let bytes = axum::body::to_bytes(body, MAX_BODY)
        .await
        .map_err(|e| Status::invalid_argument(format!("read request body: {e}")))?;
    let msg = if bytes.iter().all(u8::is_ascii_whitespace) {
        Req::default()
    } else {
        serde_json::from_slice(&bytes)
            .map_err(|e| Status::invalid_argument(format!("invalid request JSON: {e}")))?
    };
    let mut metadata = tonic::metadata::MetadataMap::new();
    if let Some(v) = parts
        .headers
        .get(header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.parse().ok())
    {
        metadata.insert("authorization", v);
    }
    let extensions = parts.extensions;
    if !intercept {
        return Ok(tonic::Request::from_parts(metadata, extensions, msg));
    }
    let checked = gw
        .interceptor
        .clone()
        .call(tonic::Request::from_parts(metadata, extensions, ()))?;
    let (metadata, extensions, ()) = checked.into_parts();
    Ok(tonic::Request::from_parts(metadata, extensions, msg))
}

fn json(status: StatusCode, body: Vec<u8>) -> Response {
    let mut resp = Response::new(Body::from(body));
    *resp.status_mut() = status;
    resp.headers_mut()
        .insert(header::CONTENT_TYPE, HeaderValue::from_static("application/json"));
    resp
}

/// grpc-gateway's error body.
#[derive(Serialize)]
struct ErrorBody<'a> {
    code: i32,
    message: &'a str,
}

fn error(status: &Status) -> Response {
    let body = ErrorBody { code: status.code() as i32, message: status.message() };
    json(http_status(status.code()), serde_json::to_vec(&body).unwrap_or_default())
}

fn result_line<T: Serialize>(msg: &T) -> Bytes {
    #[derive(Serialize)]
    struct Line<'a, T> {
        result: &'a T,
    }
    line(&Line { result: msg })
}

fn error_line(status: &Status) -> Bytes {
    #[derive(Serialize)]
    struct Line<'a> {
        error: ErrorBody<'a>,
    }
    line(&Line { error: ErrorBody { code: status.code() as i32, message: status.message() } })
}

fn line<T: Serialize>(v: &T) -> Bytes {
    let mut out = serde_json::to_vec(v).unwrap_or_default();
    out.push(b'\n');
    Bytes::from(out)
}

/// The HTTP status grpc-gateway v2 answers a gRPC code with
/// (`runtime.HTTPStatusFromCode`).
pub fn http_status(code: Code) -> StatusCode {
    match code {
        Code::Ok => StatusCode::OK,
        Code::Cancelled => StatusCode::from_u16(499).unwrap(),
        Code::Unknown | Code::Internal | Code::DataLoss => StatusCode::INTERNAL_SERVER_ERROR,
        Code::InvalidArgument | Code::FailedPrecondition | Code::OutOfRange => StatusCode::BAD_REQUEST,
        Code::DeadlineExceeded => StatusCode::GATEWAY_TIMEOUT,
        Code::NotFound => StatusCode::NOT_FOUND,
        Code::AlreadyExists | Code::Aborted => StatusCode::CONFLICT,
        Code::PermissionDenied => StatusCode::FORBIDDEN,
        Code::Unauthenticated => StatusCode::UNAUTHORIZED,
        Code::ResourceExhausted => StatusCode::TOO_MANY_REQUESTS,
        Code::Unimplemented => StatusCode::NOT_IMPLEMENTED,
        Code::Unavailable => StatusCode::SERVICE_UNAVAILABLE,
    }
}

/// A gateway call in `grpc_server_started_total` /
/// `grpc_server_handled_total`, finished once; a call dropped before
/// it finished (its client went away) counts as `Canceled`.
struct Counted {
    traffic: Arc<Traffic>,
    labels: GrpcLabels,
    done: bool,
}

impl Counted {
    fn start(traffic: &Arc<Traffic>, service: &str, method: &str, grpc_type: &str) -> Self {
        let labels = GrpcLabels {
            grpc_type: grpc_type.to_string(),
            grpc_service: format!("etcdserverpb.{service}"),
            grpc_method: method.to_string(),
        };
        traffic.grpc_started.get_or_create(&labels).inc();
        Self { traffic: traffic.clone(), labels, done: false }
    }

    fn finish(&mut self, code: Code) {
        if std::mem::replace(&mut self.done, true) {
            return;
        }
        let l = &self.labels;
        self.traffic
            .grpc_handled
            .get_or_create(&GrpcHandledLabels {
                grpc_type: l.grpc_type.clone(),
                grpc_service: l.grpc_service.clone(),
                grpc_method: l.grpc_method.clone(),
                grpc_code: code_label(code).to_string(),
            })
            .inc();
    }
}

impl Drop for Counted {
    fn drop(&mut self) {
        self.finish(Code::Cancelled);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn codes_map_to_grpc_gateway_http_statuses() {
        assert_eq!(http_status(Code::NotFound), StatusCode::NOT_FOUND);
        assert_eq!(http_status(Code::PermissionDenied), StatusCode::FORBIDDEN);
        assert_eq!(http_status(Code::Unauthenticated), StatusCode::UNAUTHORIZED);
        assert_eq!(http_status(Code::OutOfRange), StatusCode::BAD_REQUEST);
        assert_eq!(http_status(Code::FailedPrecondition), StatusCode::BAD_REQUEST);
        assert_eq!(http_status(Code::ResourceExhausted), StatusCode::TOO_MANY_REQUESTS);
        assert_eq!(http_status(Code::Unavailable), StatusCode::SERVICE_UNAVAILABLE);
        assert_eq!(http_status(Code::Cancelled).as_u16(), 499);
    }

    /// The JSON is etcd's: proto field names, 64-bit ints as strings,
    /// bytes base64, enums by name, defaults left out.
    #[test]
    fn messages_are_etcd_gateway_json() {
        let resp = pb::RangeResponse {
            header: Some(pb::ResponseHeader { cluster_id: 7, member_id: 1, revision: 2, raft_term: 3 }),
            kvs: vec![fastetcd_proto::mvccpb::KeyValue {
                key: b"foo".to_vec(),
                value: b"bar".to_vec(),
                create_revision: 2,
                mod_revision: 2,
                version: 1,
                lease: 0,
            }],
            more: false,
            count: 1,
        };
        assert_eq!(
            serde_json::to_string(&resp).unwrap(),
            r#"{"header":{"cluster_id":"7","member_id":"1","revision":"2","raft_term":"3"},"kvs":[{"key":"Zm9v","create_revision":"2","mod_revision":"2","version":"1","value":"YmFy"}],"count":"1"}"#
        );
        let status = pb::StatusResponse { db_size: 10, raft_index: 4, is_learner: false, ..Default::default() };
        assert_eq!(serde_json::to_string(&status).unwrap(), r#"{"dbSize":"10","raftIndex":"4"}"#);
        let member = pb::Member { id: 5, name: "a".into(), peer_ur_ls: vec!["http://p".into()], ..Default::default() };
        assert_eq!(serde_json::to_string(&member).unwrap(), r#"{"ID":"5","name":"a","peerURLs":["http://p"]}"#);
        let alarm = pb::AlarmMember { member_id: 1, alarm: pb::AlarmType::Nospace as i32 };
        assert_eq!(serde_json::to_string(&alarm).unwrap(), r#"{"memberID":"1","alarm":"NOSPACE"}"#);
    }

    #[test]
    fn requests_take_either_spelling_names_numbers_and_unknown_fields() {
        let r: pb::RangeRequest =
            serde_json::from_str(r#"{"key":"Zm9v","range_end":"Zm9w","keysOnly":true,"limit":5,"bogus":1}"#).unwrap();
        assert_eq!((r.key.as_slice(), r.range_end.as_slice(), r.keys_only, r.limit), (&b"foo"[..], &b"fop"[..], true, 5));
        let r: pb::RangeRequest = serde_json::from_str(r#"{"limit":"7"}"#).unwrap();
        assert_eq!(r.limit, 7);
        let a: pb::AlarmRequest =
            serde_json::from_str(r#"{"action":"DEACTIVATE","memberID":"9","alarm":"NOSPACE"}"#).unwrap();
        assert_eq!(a.action, pb::alarm_request::AlarmAction::Deactivate as i32);
        assert_eq!((a.member_id, a.alarm), (9, pb::AlarmType::Nospace as i32));
        let a: pb::AlarmRequest = serde_json::from_str(r#"{"action":0}"#).unwrap();
        assert_eq!(a.action, pb::alarm_request::AlarmAction::Get as i32);
    }
}
